<a href="https://colab.research.google.com/github/astutikumari/ML-bootcamp/blob/main/ASTUTI__data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing | Machine Learning Bootcamp

## Import the required libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [3]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Solving for missing data

In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

## Encoding categorical data

### Encoding the Independent Variable

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 0.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 0.0 40.0 62562.5]
 [0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 0.0 1.0 38.5625 52000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 1.0 37.0 67000.0]
 [1.0 0.0 1.0 0.0 0.0 25.0 62562.5]
 [1.0 0.0 0.0 0.0 1.0 36.0 60000.0]
 [1.0 0.0 0.0 1.0 0.0 42.0 64000.0]
 [1.0 0.0 1.0 0.0 0.0 38.5625 40000.0]
 [1.0 0.0 0.0 0.0 1.0 52.0 90000.0]
 [1.0 0.0 0.0 1.0 0.0 38.5625 55000.0]
 [0.0 1.0 0.0 0.0 0.0 41.0 62562.5]
 [1.0 0.0 1.0 0.0 0.0 29.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 43.0 70000.0]]


### Encoding the Dependent Variable

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 40)

In [12]:
print(X_train)

[[1.0 0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 1.0 0.0 0.0 0.0 43.0 70000.0]
 [1.0 0.0 0.0 0.0 1.0 52.0 90000.0]
 [1.0 0.0 0.0 0.0 1.0 37.0 67000.0]
 [1.0 0.0 0.0 0.0 1.0 36.0 60000.0]
 [0.0 1.0 0.0 0.0 0.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 0.0 38.5625 40000.0]
 [1.0 0.0 1.0 0.0 0.0 29.0 48000.0]
 [1.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 0.0 38.5625 55000.0]
 [1.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 0.0 1.0 38.5625 52000.0]]


In [15]:
print(X_test)

[[0.0 1.0 0.0 0.0 0.0 41.0 62562.5]
 [1.0 0.0 1.0 0.0 0.0 25.0 62562.5]
 [1.0 0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 1.0 0.0 0.0 44.0 72000.0]]


In [13]:
print(y_train)

[1 1 1 1 0 0 1 0 1 0 0 0 1 1 0]


In [14]:
print(y_test)

[1 0 1 0]


## Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
print(X_train)

[[ 0.5        -0.5        -0.5         1.6583124  -0.70710678  0.44570485
   0.15355946]
 [-2.          2.         -0.5        -0.60302269 -0.70710678  0.58701154
   0.59937724]
 [ 0.5        -0.5        -0.5        -0.60302269  1.41421356  1.85877174
   2.08543652]
 [ 0.5        -0.5        -0.5        -0.60302269  1.41421356 -0.2608286
   0.37646835]
 [ 0.5        -0.5        -0.5        -0.60302269  1.41421356 -0.40213529
  -0.1436524 ]
 [-2.          2.         -0.5        -0.60302269 -0.70710678 -0.11952191
  -0.06934943]
 [ 0.5        -0.5         2.         -0.60302269 -0.70710678 -0.0400369
  -1.62971168]
 [ 0.5        -0.5         2.         -0.60302269 -0.70710678 -1.39128211
  -1.03528797]
 [ 0.5        -0.5        -0.5        -0.60302269  1.41421356 -1.67389549
  -1.03528797]
 [ 0.5        -0.5        -0.5         1.6583124  -0.70710678 -1.24997542
  -0.58947018]
 [ 0.5        -0.5        -0.5         1.6583124  -0.70710678 -0.0400369
  -0.51516722]
 [ 0.5        -0.5      

In [18]:
print(X_test)

[[-2.          2.         -0.5        -0.60302269 -0.70710678  0.30439816
   0.04674895]
 [ 0.5        -0.5         2.         -0.60302269 -0.70710678 -1.95650887
   0.04674895]
 [ 0.5        -0.5         2.         -0.60302269 -0.70710678  0.16309147
   0.04674895]
 [ 0.5        -0.5         2.         -0.60302269 -0.70710678  0.72831823
   0.74798317]]
